TRAEFIK_BRIDGE ?= traefiknet
USER_UID ?= $(shell id -ur)
USER_GID ?= $(shell id -gr)
NAME ?= prestashop
HOSTNAME ?= $(NAME).docker.localhost
MYSQL_SERVER ?= db
MYSQL_IMAGE ?= amery/docker-alpine-mariadb
MYSQL_DATABASE ?= $(NAME)
MYSQL_USER ?= $(MYSQL_DATABASE)
MYSQL_PASSWORD ?= prestashop
MYSQL_ROOT_PASSWORD ?= $(MYSQL_PASSWORD)
PS_DISABLE_MAKE ?= 0
PS_INSTALL_AUTO ?= 1
PS_FOLDER_INSTALL ?= install-dev
PS_FOLDER_ADMIN ?= admin-dev
