TRAEFIK_BRIDGE ?= traefiknet
USER_UID ?= $(shell id -ur)
USER_GID ?= $(shell id -gr)
NAME ?= prestashop
HOSTNAME ?= $(NAME).docker.localhost
NGINX_IMAGE ?= amery/docker-alpine-nginx
PHP_IMAGE ?= amery/docker-alpine-php7:latest
PHP_MEMORY_LIMIT ?= 4G
PHP_MAX_UPLOAD_MB ?= 16
MYSQL_SERVER ?= db
MYSQL_PORT ?=
MYSQL_IMAGE ?= amery/docker-alpine-mariadb
MYSQL_DATABASE ?= $(NAME)
MYSQL_USER ?= $(MYSQL_DATABASE)
MYSQL_PASSWORD ?= db_user_password
MYSQL_ROOT_PASSWORD ?= db_root_password
PS_DISABLE_MAKE ?= 0
PS_INSTALL_AUTO ?= 1
PS_DB_PREFIX ?=
PS_FOLDER_INSTALL ?= install-dev
PS_FOLDER_ADMIN ?= admin-dev
PS_PROJECT_PATH ?= /srv/http/prestashop
PS_LANGUAGE ?=
PS_ALL_LANGUAGES ?=
PS_COUNTRY ?=
PS_ADMIN_EMAIL ?= admin@example.org
PS_ADMIN_PASSWD ?= admin_password
