# vim: set ft=dockerfile ts=4 sw=4 et:
FROM @@PHP_IMAGE@@

#
# extra php dependencies
#
RUN apk --update upgrade -U && apk --no-cache add \
    php7-curl \
    php7-dom \
    php7-fileinfo \
    php7-gd \
    php7-iconv \
    php7-intl \
    php7-json \
    php7-mbstring \
    php7-openssl \
    php7-pdo \
    php7-pdo_mysql \
    php7-simplexml \
    php7-tokenizer \
    php7-xmlreader \
    php7-xmlwriter \
    php7-zip

#
# bash and node.js needed to build assets
#
ENV NPM_VERSION=8.1.3

RUN apk --update upgrade -U && apk --no-cache add \
        bash \
        npm \
    && npm i -g \
        npm@${NPM_VERSION} \
    && rm -rf ~/.npm

#
# setup
#
COPY prestashop.sh /etc/entrypoint.d/
